### ISSUE TITLE
Missing GPA point values in student report card

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#83]
See below. To reproduce use the SQL dump or login at https://misis.pss.edu.mh/training/index.php with teacher kosborne and the password I sent by email.

![Missing GPA point values](https://user-images.githubusercontent.com/1091769/61086004-d56ff280-a485-11e9-931c-f774cce2c9b1.PNG)

All other users here that made it to reports so far are seeing this.

**Comment by openSISAdmin** [comment]
Resolved

**Comment by ghachey** [comment]
I still have no GPA values. Is this because of missing store procs or function?

**Comment by ghachey** [comment]
I have loaded the stored procs and functions and I still see this problem. I will send a sql dump of what I am currently using.

**Comment by openSISAdmin** [comment]
Reopened as per Ghislain's request

**Comment by openSISAdmin** [comment]
Looks like the GPA is not showing because of those course periods do not have Credit hours filled in. System won't allow entering after the course has been graded. You can do it from the database.
